visual_servo:
  
  camera_fov: 90
  compensate_roll_and_pitch: false
  yaw_added_offset: 0.0
  filter_k: 0.05

  rate_limiters:
    distance:
      rate_limiter_R: 0.5
      rate_limiter_F: -2.0
      rate_limiter_T: 0.02

    height:
      rate_limiter_R: 0.5
      rate_limiter_T: 0.02

    yaw:
      rate_limiter_R: 0.1
      rate_limiter_T: 0.02

  pid_x:
    x_armed:  false
    kp:  0.1
    ki:  0
    kd:  0
    lim_low: -0.75
    lim_high: 0.75
    deadzone_x: 0 

  pid_y:
    y_armed:  true
    kp:  0.4
    ki:  0
    kd:  0
    lim_low: -3.0
    lim_high: 3.0
    deadzone_y: 0

  pid_z:  
    z_armed: true
    kp:  0.8
    ki:  0
    kd:  0  
    lim_low: -2.0
    lim_high: 2.0
    deadzone_z: 0

  pid_yaw:
    yaw_armed: true
    kp:  0.3
    ki:  0.0
    kd:  0
    lim_low: -0.5
    lim_high: 0.5
    deadzone_yaw: 0
